strategies:
  ES:
    - trend_pullback_vwap_ema
    - compression_breakout
    - liquidity_sweep_reversal

  SILVER:
    - trend_pullback_vwap_ema
    - compression_breakout
    - liquidity_sweep_reversal

  BRENT:
    - trend_pullback_vwap_ema
    - compression_breakout
    - liquidity_sweep_reversal


